// Code generated by mockery v2.49.0. DO NOT EDIT.

package mocks

import (
	entity "event-booking/internal/entity"

	mock "github.com/stretchr/testify/mock"
)

// BookingRepository is an autogenerated mock type for the BookingRepository type
type BookingRepository struct {
	mock.Mock
}

// FindByUserID provides a mock function with given fields: userID
func (_m *BookingRepository) FindByUserID(userID string) ([]entity.Booking, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserID")
	}

	var r0 []entity.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]entity.Booking, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(string) []entity.Booking); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Booking)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewBookingRepository creates a new instance of BookingRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBookingRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *BookingRepository {
	mock := &BookingRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
